name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grammar Compilation
      id: grammar-compilation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Grammar Compilation
        setup-command: mvn clean antlr4:antlr4 compile
        command: ls src/main/java/edu/eam/ingesoft/tlf/RoboLang*.java | wc -l | awk '$1 >= 2 {exit 0} {exit 1}'
        timeout: 15
        max-score: 30
    - name: Grammar Test Execution
      id: grammar-test-execution
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Grammar Test Execution
        setup-command: ''
        command: mvn test
        timeout: 30
        max-score: 70
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRAMMAR-COMPILATION_RESULTS: "${{steps.grammar-compilation.outputs.result}}"
        GRAMMAR-TEST-EXECUTION_RESULTS: "${{steps.grammar-test-execution.outputs.result}}"
      with:
        runners: grammar-compilation,grammar-test-execution